name="CombinableItems";
tooltip="CombinableItems";
overview="Combinable repair items + bandages.";
picture="CombinableItems\data\picture.paa";
logoSmall="CombinableItems\data\logoSmall.paa";
logo="CombinableItems\data\logo.paa";
logoOver="CombinableItems\data\logo.paa";
action="https://steamcommunity.com/sharedfiles/filedetails/?id=3637996858";
author="moldypenguins";
version="1.2";
